name: Auto Tag

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump minor version
        id: bump_version
        run: |
          git fetch --tags
          latest=$(git tag -l "release/*" --sort=-v:refname | head -n 1 | sed 's/release\///')
          latest=${latest:-0.0.0}
          major=$(echo $latest | cut -d. -f1)
          minor=$(echo $latest | cut -d. -f2)
          new_version="$major.$((minor+1)).0"
          new_tag="release/$new_version"
          git tag $new_tag
          git push origin $new_tag
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
  docker:
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}},value=${{ needs.tag.outputs.new_version }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ needs.tag.outputs.new_version }}
          labels: ${{ steps.meta.outputs.labels }}