name: Auto Tag

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      #      - name: Run Bumpy
      #        uses: docker://docker.io/ch4s3r/bumpy:latest
      - name: Bump minor version
        run: |
          git fetch --tags
          latest=$(git tag -l "release/*" --sort=-v:refname | head -n 1 | sed 's/release\///')
          latest=${latest:-0.0.0}
          major=$(echo $latest | cut -d. -f1)
          minor=$(echo $latest | cut -d. -f2)
          new_tag="release/$major.$((minor+1)).0"
          git tag $new_tag
          git push origin $new_tag
  docker:
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}