name: Auto Tag

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git fetch --tags
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          major=$(echo $latest | cut -d. -f1)
          minor=$(echo $latest | cut -d. -f2)
          new_tag="$major.$((minor+1)).0"
          git tag $new_tag
          git push origin $new_tag
