name: Install Cypress Dependencies

on:
  workflow_dispatch:

jobs:
  install-cypress-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get update
      - id: apt-key
        run: echo "hash=$(sha256sum /var/lib/apt/lists/*Packages 2>/dev/null | sha256sum | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        with:
          path: ~/apt-cache
          key: apt-cypress-${{ steps.apt-key.outputs.hash }}
      - run: |
          mkdir -p ~/apt-cache/partial
          sudo apt-get -y -o Dir::Cache::Archives="$HOME/apt-cache" -o APT::Keep-Downloaded-Packages=true install libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
      - run: apt list --installed
