name: Install Cypress Dependencies

on:
  workflow_dispatch:

jobs:
  install-cypress-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix profile add nixpkgs#devenv
      - run: devenv shell -- cypress version
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: --no-sandbox
